"""add edge sync batches

Revision ID: 1dd6c0f19eba
Revises: 85ff9f8e896d
Create Date: 2026-07-18 21:04:58.059770
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '1dd6c0f19eba'
down_revision: Union[str, None] = '85ff9f8e896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_sync_batches',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('edge_node_id', sa.String(length=36), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edge_node_id'], ['edge_nodes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'edge_node_id', 'deduplication_key', name='uq_edge_sync_batch_dedup')
    )
    op.create_index(op.f('ix_edge_sync_batches_deduplication_key'), 'edge_sync_batches', ['deduplication_key'], unique=False)
    op.create_index(op.f('ix_edge_sync_batches_edge_node_id'), 'edge_sync_batches', ['edge_node_id'], unique=False)
    op.create_index(op.f('ix_edge_sync_batches_organization_id'), 'edge_sync_batches', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_sync_batches_organization_id'), table_name='edge_sync_batches')
    op.drop_index(op.f('ix_edge_sync_batches_edge_node_id'), table_name='edge_sync_batches')
    op.drop_index(op.f('ix_edge_sync_batches_deduplication_key'), table_name='edge_sync_batches')
    op.drop_table('edge_sync_batches')
    # ### end Alembic commands ###
