"""initial schema

Revision ID: 67a20ecf2d25
Revises: 
Create Date: 2026-07-18 20:42:28.589233
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '67a20ecf2d25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('organization_type', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('airports',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'iata_code', name='uq_airport_org_iata')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airports_organization_id'), 'airports', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('new_state', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('ip_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('edge_nodes',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration_version', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.JSON(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_nodes_organization_id'), 'edge_nodes', ['organization_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('framework', sa.String(length=40), nullable=False),
    sa.Column('input_resolution', sa.String(length=32), nullable=False),
    sa.Column('class_list', sa.JSON(), nullable=False),
    sa.Column('checkpoint_path', sa.Text(), nullable=True),
    sa.Column('checkpoint_checksum', sa.String(length=64), nullable=True),
    sa.Column('validation_metrics', sa.JSON(), nullable=False),
    sa.Column('deployment_status', sa.String(length=32), nullable=False),
    sa.Column('safe_serialization', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_organization_id'), 'model_versions', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_role'), 'organization_memberships', ['role'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=False),
    sa.Column('corrected_value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_organization_id'), 'review_decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_resource_id'), 'review_decisions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_reviewer_id'), 'review_decisions', ['reviewer_id'], unique=False)
    op.create_table('terminals',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminals_airport_id'), 'terminals', ['airport_id'], unique=False)
    op.create_index(op.f('ix_terminals_organization_id'), 'terminals', ['organization_id'], unique=False)
    op.create_table('stands',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('terminal_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_id', 'code', name='uq_stand_airport_code')
    )
    op.create_index(op.f('ix_stands_airport_id'), 'stands', ['airport_id'], unique=False)
    op.create_index(op.f('ix_stands_code'), 'stands', ['code'], unique=False)
    op.create_index(op.f('ix_stands_organization_id'), 'stands', ['organization_id'], unique=False)
    op.create_table('cameras',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('stand_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_mode', sa.String(length=32), nullable=False),
    sa.Column('stream_url_encrypted', sa.Text(), nullable=True),
    sa.Column('camera_type', sa.String(length=64), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('frame_rate', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calibration_state', sa.String(length=32), nullable=False),
    sa.Column('masked_regions', sa.JSON(), nullable=False),
    sa.Column('privacy_regions', sa.JSON(), nullable=False),
    sa.Column('processing_profile', sa.JSON(), nullable=False),
    sa.Column('retention_settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_airport_id'), 'cameras', ['airport_id'], unique=False)
    op.create_index(op.f('ix_cameras_organization_id'), 'cameras', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cameras_stand_id'), 'cameras', ['stand_id'], unique=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.create_table('turnarounds',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('stand_id', sa.String(length=36), nullable=False),
    sa.Column('airline_code', sa.String(length=8), nullable=False),
    sa.Column('flight_number', sa.String(length=32), nullable=False),
    sa.Column('aircraft_registration', sa.String(length=32), nullable=True),
    sa.Column('aircraft_type', sa.String(length=64), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_on_block', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_off_block', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('manual_review_state', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnarounds_airport_id'), 'turnarounds', ['airport_id'], unique=False)
    op.create_index(op.f('ix_turnarounds_flight_number'), 'turnarounds', ['flight_number'], unique=False)
    op.create_index(op.f('ix_turnarounds_organization_id'), 'turnarounds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_turnarounds_stand_id'), 'turnarounds', ['stand_id'], unique=False)
    op.create_index(op.f('ix_turnarounds_status'), 'turnarounds', ['status'], unique=False)
    op.create_table('camera_calibrations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reference_points', sa.JSON(), nullable=False),
    sa.Column('homography_matrix', sa.JSON(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('ground_plane_units', sa.String(length=16), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('error_estimate', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_calibrations_camera_id'), 'camera_calibrations', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_calibrations_organization_id'), 'camera_calibrations', ['organization_id'], unique=False)
    op.create_table('camera_zones',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('stand_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('zone_type', sa.String(length=64), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('allowed_classes', sa.JSON(), nullable=False),
    sa.Column('forbidden_classes', sa.JSON(), nullable=False),
    sa.Column('rule_configuration', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_zones_camera_id'), 'camera_zones', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_zones_organization_id'), 'camera_zones', ['organization_id'], unique=False)
    op.create_index(op.f('ix_camera_zones_zone_type'), 'camera_zones', ['zone_type'], unique=False)
    op.create_table('turnaround_milestones',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('turnaround_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_type', sa.String(length=80), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('observation_kind', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_track_ids', sa.JSON(), nullable=False),
    sa.Column('original_prediction', sa.JSON(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['turnaround_id'], ['turnarounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnaround_milestones_milestone_type'), 'turnaround_milestones', ['milestone_type'], unique=False)
    op.create_index(op.f('ix_turnaround_milestones_organization_id'), 'turnaround_milestones', ['organization_id'], unique=False)
    op.create_index(op.f('ix_turnaround_milestones_turnaround_id'), 'turnaround_milestones', ['turnaround_id'], unique=False)
    op.create_table('uploaded_videos',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_videos_camera_id'), 'uploaded_videos', ['camera_id'], unique=False)
    op.create_index(op.f('ix_uploaded_videos_organization_id'), 'uploaded_videos', ['organization_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('turnaround_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('detector_backend', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['turnaround_id'], ['turnarounds.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['uploaded_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_camera_id'), 'processing_jobs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_organization_id'), 'processing_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_video_id'), 'processing_jobs', ['video_id'], unique=False)
    op.create_table('safety_rules',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('cooldown_seconds', sa.Float(), nullable=False),
    sa.Column('debounce_seconds', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['camera_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_rules_camera_id'), 'safety_rules', ['camera_id'], unique=False)
    op.create_index(op.f('ix_safety_rules_organization_id'), 'safety_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_safety_rules_rule_type'), 'safety_rules', ['rule_type'], unique=False)
    op.create_table('object_tracks',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('processing_job_id', sa.String(length=36), nullable=True),
    sa.Column('turnaround_id', sa.String(length=36), nullable=True),
    sa.Column('external_track_id', sa.Integer(), nullable=False),
    sa.Column('object_class', sa.String(length=80), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('confidence_mean', sa.Float(), nullable=False),
    sa.Column('bbox_history_path', sa.Text(), nullable=True),
    sa.Column('centroid_history', sa.JSON(), nullable=False),
    sa.Column('velocity_summary', sa.JSON(), nullable=False),
    sa.Column('zone_history', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['turnaround_id'], ['turnarounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_tracks_camera_id'), 'object_tracks', ['camera_id'], unique=False)
    op.create_index(op.f('ix_object_tracks_object_class'), 'object_tracks', ['object_class'], unique=False)
    op.create_index(op.f('ix_object_tracks_organization_id'), 'object_tracks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_object_tracks_processing_job_id'), 'object_tracks', ['processing_job_id'], unique=False)
    op.create_index('ix_track_job_external', 'object_tracks', ['processing_job_id', 'external_track_id'], unique=False)
    op.create_table('operational_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('processing_job_id', sa.String(length=36), nullable=True),
    sa.Column('turnaround_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('observation_kind', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_track_ids', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['turnaround_id'], ['turnarounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_events_camera_id'), 'operational_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_operational_events_event_type'), 'operational_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_operational_events_organization_id'), 'operational_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_operational_events_processing_job_id'), 'operational_events', ['processing_job_id'], unique=False)
    op.create_table('safety_alerts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('stand_id', sa.String(length=36), nullable=True),
    sa.Column('turnaround_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('related_track_ids', sa.JSON(), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_snapshot_path', sa.Text(), nullable=True),
    sa.Column('evidence_clip_path', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['safety_rules.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.id'], ),
    sa.ForeignKeyConstraint(['turnaround_id'], ['turnarounds.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['camera_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_org_status_time', 'safety_alerts', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_safety_alerts_camera_id'), 'safety_alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_safety_alerts_deduplication_key'), 'safety_alerts', ['deduplication_key'], unique=False)
    op.create_index(op.f('ix_safety_alerts_organization_id'), 'safety_alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_safety_alerts_rule_id'), 'safety_alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_safety_alerts_severity'), 'safety_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_safety_alerts_status'), 'safety_alerts', ['status'], unique=False)
    op.create_table('evidence_assets',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['safety_alerts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_assets_organization_id'), 'evidence_assets', ['organization_id'], unique=False)
    op.create_table('incidents',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['safety_alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_alert_id'), 'incidents', ['alert_id'], unique=False)
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_alert_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_evidence_assets_organization_id'), table_name='evidence_assets')
    op.drop_table('evidence_assets')
    op.drop_index(op.f('ix_safety_alerts_status'), table_name='safety_alerts')
    op.drop_index(op.f('ix_safety_alerts_severity'), table_name='safety_alerts')
    op.drop_index(op.f('ix_safety_alerts_rule_id'), table_name='safety_alerts')
    op.drop_index(op.f('ix_safety_alerts_organization_id'), table_name='safety_alerts')
    op.drop_index(op.f('ix_safety_alerts_deduplication_key'), table_name='safety_alerts')
    op.drop_index(op.f('ix_safety_alerts_camera_id'), table_name='safety_alerts')
    op.drop_index('ix_alert_org_status_time', table_name='safety_alerts')
    op.drop_table('safety_alerts')
    op.drop_index(op.f('ix_operational_events_processing_job_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_organization_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_event_type'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_camera_id'), table_name='operational_events')
    op.drop_table('operational_events')
    op.drop_index('ix_track_job_external', table_name='object_tracks')
    op.drop_index(op.f('ix_object_tracks_processing_job_id'), table_name='object_tracks')
    op.drop_index(op.f('ix_object_tracks_organization_id'), table_name='object_tracks')
    op.drop_index(op.f('ix_object_tracks_object_class'), table_name='object_tracks')
    op.drop_index(op.f('ix_object_tracks_camera_id'), table_name='object_tracks')
    op.drop_table('object_tracks')
    op.drop_index(op.f('ix_safety_rules_rule_type'), table_name='safety_rules')
    op.drop_index(op.f('ix_safety_rules_organization_id'), table_name='safety_rules')
    op.drop_index(op.f('ix_safety_rules_camera_id'), table_name='safety_rules')
    op.drop_table('safety_rules')
    op.drop_index(op.f('ix_processing_jobs_video_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_organization_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_camera_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_uploaded_videos_organization_id'), table_name='uploaded_videos')
    op.drop_index(op.f('ix_uploaded_videos_camera_id'), table_name='uploaded_videos')
    op.drop_table('uploaded_videos')
    op.drop_index(op.f('ix_turnaround_milestones_turnaround_id'), table_name='turnaround_milestones')
    op.drop_index(op.f('ix_turnaround_milestones_organization_id'), table_name='turnaround_milestones')
    op.drop_index(op.f('ix_turnaround_milestones_milestone_type'), table_name='turnaround_milestones')
    op.drop_table('turnaround_milestones')
    op.drop_index(op.f('ix_camera_zones_zone_type'), table_name='camera_zones')
    op.drop_index(op.f('ix_camera_zones_organization_id'), table_name='camera_zones')
    op.drop_index(op.f('ix_camera_zones_camera_id'), table_name='camera_zones')
    op.drop_table('camera_zones')
    op.drop_index(op.f('ix_camera_calibrations_organization_id'), table_name='camera_calibrations')
    op.drop_index(op.f('ix_camera_calibrations_camera_id'), table_name='camera_calibrations')
    op.drop_table('camera_calibrations')
    op.drop_index(op.f('ix_turnarounds_status'), table_name='turnarounds')
    op.drop_index(op.f('ix_turnarounds_stand_id'), table_name='turnarounds')
    op.drop_index(op.f('ix_turnarounds_organization_id'), table_name='turnarounds')
    op.drop_index(op.f('ix_turnarounds_flight_number'), table_name='turnarounds')
    op.drop_index(op.f('ix_turnarounds_airport_id'), table_name='turnarounds')
    op.drop_table('turnarounds')
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_stand_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_organization_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_airport_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_stands_organization_id'), table_name='stands')
    op.drop_index(op.f('ix_stands_code'), table_name='stands')
    op.drop_index(op.f('ix_stands_airport_id'), table_name='stands')
    op.drop_table('stands')
    op.drop_index(op.f('ix_terminals_organization_id'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_airport_id'), table_name='terminals')
    op.drop_table('terminals')
    op.drop_index(op.f('ix_review_decisions_reviewer_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_resource_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_organization_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_role'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_model_versions_organization_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_edge_nodes_organization_id'), table_name='edge_nodes')
    op.drop_table('edge_nodes')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_airports_organization_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
