"""add incident notes

Revision ID: 85ff9f8e896d
Revises: 67a20ecf2d25
Create Date: 2026-07-18 21:01:47.008653
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '85ff9f8e896d'
down_revision: Union[str, None] = '67a20ecf2d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_notes',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_notes_author_id'), 'incident_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_incident_notes_incident_id'), 'incident_notes', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_notes_organization_id'), 'incident_notes', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_notes_organization_id'), table_name='incident_notes')
    op.drop_index(op.f('ix_incident_notes_incident_id'), table_name='incident_notes')
    op.drop_index(op.f('ix_incident_notes_author_id'), table_name='incident_notes')
    op.drop_table('incident_notes')
    # ### end Alembic commands ###
