"""add model deployments

Revision ID: ec07fad70414
Revises: 1dd6c0f19eba
Create Date: 2026-07-18 21:11:45.091027
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ec07fad70414'
down_revision: Union[str, None] = '1dd6c0f19eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_deployments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=True),
    sa.Column('edge_node_id', sa.String(length=36), nullable=True),
    sa.Column('backend', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployed_by_id', sa.String(length=36), nullable=False),
    sa.Column('rollback_of_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['deployed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edge_node_id'], ['edge_nodes.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['rollback_of_id'], ['model_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_deployments_camera_id'), 'model_deployments', ['camera_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_deployed_by_id'), 'model_deployments', ['deployed_by_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_edge_node_id'), 'model_deployments', ['edge_node_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_model_version_id'), 'model_deployments', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_organization_id'), 'model_deployments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_model_deployments_status'), 'model_deployments', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_deployments_status'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_organization_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_model_version_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_edge_node_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_deployed_by_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_camera_id'), table_name='model_deployments')
    op.drop_table('model_deployments')
    # ### end Alembic commands ###
